const workspacesData = [
    {
      id: "1",
      name: "North Delhi",
      organization: "Org 1",
      tags: "Tag 1",
      description: "Description of Workspace 1",
      publishedOn: "Dec 19, 2024",
      modifiedOn: "Dec 29, 2024",
      users: 1,
      domains: 0,
      dataSources: 0,
      pendingApprovals: 3,
      type: 'owned'
    },
    {
      id: "2",
      name: "Pune",
      organization: "Org 2",
      tags: "Tag 2",
      description: "Description of Workspace 2",
      publishedOn: "Dec 20, 2024",
      modifiedOn: "Dec 20, 2024",
      users: 3,
      domains: 1,
      dataSources: 1,
      pendingApprovals: 7,
      type: 'external'
    },
    {
      id: "3",
      name: "Mumbai",
      organization: "Org 3",
      tags: "Tag 3",
      description: "Description of Workspace 3",
      publishedOn: "Dec 11, 2024",
      modifiedOn: "Dec 11, 2024",
      users: 3,
      domains: 0,
      dataSources: 0,
      pendingApprovals: 0,
      type: 'owned'
    },
    {
      id: "4",
      name: "Bangalore",
      organization: "Org 4",
      tags: "Tag 4",
      description: "Description of Workspace 4",
      publishedOn: "Dec 24, 2024",
      modifiedOn: "Dec 24, 2024",
      users: 4,
      domains: 1,
      dataSources: 2,
      pendingApprovals: 1,
      type: 'external'
    },
    {
      id: "5",
      name: "South Delhi",
      organization: "Org 5",
      tags: "Tag 5",
      description: "Description of Workspace 5",
      publishedOn: "Aug 24, 2024",
      modifiedOn: "Sep 24, 2024",
      users: 1,
      domains: 5,
      dataSources: 0,
      pendingApprovals: 12,
      type: 'external'
    },
    {
      id: "6",
      name: "Lucknow",
      organization: "Org 6",
      tags: "Tag 6",
      description: "Description of Workspace 6",
      publishedOn: "Dec 10, 2004",
      modifiedOn: "Dec 29, 2004",
      users: 6,
      domains: 0,
      dataSources: 0,
      pendingApprovals: 3,
      type: 'owned'
    },
    {
      id: "7",
      name: "Bhopal",
      organization: "Org 7",
      tags: "Tag 7",
      description: "Description of Workspace 7",
      publishedOn: "May 02, 2024",
      modifiedOn: "May 02, 2024",
      users: 3,
      domains: 10,
      dataSources: 1,
      pendingApprovals: 17,
      type: 'external'
    },
    {
      id: "8",
      name: "Surat Gujrat",
      organization: "Org 8",
      tags: "Tag 8",
      description: "Description of Workspace 8",
      publishedOn: "Jun 30, 2020",
      modifiedOn: "Jun 30, 2020",
      users: 2,
      domains: 6,
      dataSources: 12,
      pendingApprovals: 0,
      type: 'owned'
    },
    {
      id: "9",
      name: "Nepal",
      organization: "Org 9",
      tags: "Tag 9",
      description: "Description of Workspace 9",
      publishedOn: "Apr 04, 2015",
      modifiedOn: "Apr 04, 2015",
      users: 19,
      domains: 14,
      dataSources: 22,
      pendingApprovals: 0,
      type: 'external'
    },
    {
      id: "10",
      name: "Vadodara Gujrat",
      organization: "Org 10",
      tags: "Tag 10",
      description: "Description of Workspace 10",
      publishedOn: "Aug 24, 2024",
      modifiedOn: "Sep 24, 2024",
      users: 11,
      domains: 30,
      dataSources: 0,
      pendingApprovals: 2,
      type: 'external'
    },
    {
      id: "11",
      name: "Kanpur",
      organization: "Org 11",
      tags: "Tag 11",
      description: "Description of Workspace 11",
      publishedOn: "Aug 24, 2024",
      modifiedOn: "Sep 24, 2024",
      users: 11,
      domains: 0,
      dataSources: 3,
      pendingApprovals: 2,
      type: 'owned'
    },
  ];
  
  export default workspacesData;
  